name: Deploy to AWS

on:
  push:
    branches:
      - main

env:
  ACTIONS_STEP_DEBUG: true
  AWS_DEBUG: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: us-east-1
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - name: Terraform Init Backend Bucket
        run: terraform init
        working-directory: ./terraform/backend

      - name: Terraform Apply Backend
        run: terraform apply -auto-approve
        working-directory: ./terraform/backend

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
      
      - name: Read destroy.txt
        id: check_destroy
        run: |
          DESTROY=$(cat destroy.txt)
          echo "Destroy value: $DESTROY"
          echo "destroy_flag=$DESTROY" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: Terraform Destroy
        if: env.destroy_flag == 'true'
        run: |
          terraform destroy -var="cognito_email=${{ secrets.COGNITO_EMAIL }}" -var="cognito_password=${{ secrets.COGNITO_PWD }}" -auto-approve
          exit 0
        working-directory: ./terraform

      - name: Terraform Apply
        if: env.destroy_flag != 'true'
        run: terraform apply -var="cognito_email=${{ secrets.COGNITO_EMAIL }}" -var="cognito_password=${{ secrets.COGNITO_PWD }}" -auto-approve
        working-directory: ./terraform

      - name: Destroy Terraform resources if anything goes wrong
        run: terraform destroy -var="cognito_email=${{ secrets.COGNITO_EMAIL }}" -var="cognito_password=${{ secrets.COGNITO_PWD }}" -auto-approve
        working-directory: ./terraform
        if: failure()  
